version: "3.8"

services:
  db:
    image: postgres:15
    container_name: computer_shop_pg
    environment:
      POSTGRES_DB: computer_shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
